#!/usr/bin/env bash
set -euo pipefail

usage="$(basename "$0") [-h] [size] [target] -- create random file

OPTIONS:
    -h		Show this help message

FUNCTION:
    size	Size in byte or human readable format, optional.
    target	Target file or directory, optional.
"
usage() {
    echo "$usage"
    exit 1
}

for option in "$@"
do
    case $option in
        -h|--help) usage;;
        \?) printf "illegal option: -%s\n" "$OPTARG" >&2; usage;;
    esac
done

if [ $OPTIND -gt 1 ]; then shift $((OPTIND - 1)); fi
if [ $# -gt 2 ]; then usage; fi

##

# Optional: user specified file size
if test -z "$1"
then
    # default size
    file_size=`dehumanise 1M`
else
    file_size=`dehumanise $1`
fi

if test -z "$file_size"
then
    echo "ERROR: could not parse given size"
    usage
    exit 1
fi

# Optional: user specified target file
if test -z "$2"
then
    file_name="/tmp/randfile.`echo date$$ | md5`"
elif [[ -f $2 ]]
then
    # file already exists
    echo "ERROR: target file already exists"
    exit 1
elif [[ -d $2 ]]
then
    file_name="`realpath $2`/randfile.`echo date$$ | md5`"
else
    file_name=$2
fi

if test -z "$file_name"
then
    echo "ERROR: could not parse given path"
    usage
    exit 1
fi


# print file information
echo "Generating test file ..."
echo "  File: $file_name"
echo "  Size: `humanise $file_size` ..."
`dd if=/dev/urandom of=$file_name bs=$(echo "$file_size" | bc) count=1 &> /dev/null`

exit $?
